server:
  port: 8080
  error:
    include:
      message: true

grpc:
  server:
    max-inbound-message-size: 9155241000
  client:
    grpcGeoClient:
      address: 'static://localhost:9099'
      negotiationType: PLAINTEXT
    grpcPhotoClient:
      address: 'static://localhost:9089'
      negotiationType: PLAINTEXT
      max-inbound-message-size: 9155241000
      package-max-inbound-message-size: 9155241000

spring:
  application:
    name: rangiffler-gateway

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG

---
spring:
  config:
    activate:
      on-profile: 'local'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://127.0.0.1:9000'

rangiffler-geo:
  base-uri: 'http://127.0.0.1:8088'
rangiffler-userdata:
  base-uri: 'http://127.0.0.1:8089'
rangiffler-photo:
  base-uri: 'http://127.0.0.1:8086'
rangiffler-client:
  base-uri: 'http://127.0.0.1:3001'

---
spring:
  config:
    activate:
      on-profile: 'docker'
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: 'http://rangiffler-auth:9000'

rangiffler-geo:
  base-uri: 'http://rangiffler-geo:8088'
rangiffler-userdata:
  base-uri: 'http://rangiffler-userdata:8089'
rangiffler-photo:
  base-uri: 'http://rangiffler-photo:8086'
rangiffler-client:
  base-uri: 'http://127.0.0.1'
---
